### ISSUE TITLE
Algorithm class not found

### ISSUE THREAD

**Issue by fazleskhan** [fazleskhan/algorithmia_SieveOfEratosthenes#1]
When trying to run the build below via the Algorithimia console the error below occured

https://algorithmia.com/algorithms/fazleskhan/algorithmia_SieveOfEratosthenes/builds/c0735cc6-6675-4ed3-8ccd-a2a48d713278  

> Error: Failed to start algorithm - Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
com.algorithmia.JarRunner$AlgorithmiaRunnerException: Algorithm class not found. Name must match: algorithmia.algorithmia_SieveOfEratosthenes.algorithmia_SieveOfEratosthenes
To Fix: Double check both package-name and class-name
	at com.algorithmia.JarRunner.loadAlgorithm(JarRunner.java:231)
	at com.algorithmia.JarRunner.<init>(JarRunner.java:39)
	at com.algorithmia.Pipe.main(Pipe.java:51)
2020-02-20T17:12:38.186 INFO ALGOERR -
Failed to load: exited with code 1
>

**Comment by fazleskhan** [comment]
The build artifacts were not being copied to the parent project. Once the copy goal was added to each submodule the Algorithmia build picked them up
